//                                                                             
// File:       soc_miner_regs.v                                                
// Creator:    jorgem                                                          
// Time:       Monday Sep 30, 2013 [6:23:45 pm]                                
//                                                                             
// Path:       /v/049/share02/jorgem/bitcoin/SocMiner/hw/rdl                   
// Arguments:  /apps/cadence/blueprint/blueprint_3.7.5/Linux-64bit/blueprint   
//             -regbus soc_miner_regs.rdl                                      
//                                                                             
// Sources:    /v/049/share02/jorgem/bitcoin/SocMiner/hw/rdl/soc_miner_regs.rdl
//             /h/jorgem/ae/asic_tools/bp_gens/regbus.pm                       
//             /h/jorgem/ae/asic_tools/bp_gens/vutils.pm                       
//             /h/jorgem/ae/asic_tools/bp_gens/verilog.pm                      
//                                                                             
// Blueprint:   3.7.5 (Wed Feb 1 23:58:40 PST 2012)                            
// Machine:    vl155.cce.hp.com                                                
// OS:         Linux 2.6.18-308.el5                                            
// Description:                                                                
//                                                                             
// No Description Provided                                                     
//                                                                             
// Copyright (C) 2013 Denali Software Inc.  All rights reserved                
// THIS FILE IS AUTOMATICALLY GENERATED BY DENALI BLUEPRINT, DO NOT EDIT       
//                                                                             


module soc_miner_regs (
  Clk,
  RegBus_read,
  RegBus_val,
  RegBus_write_data,
  RegBus_address,
  control_go_next,
  RESET,

  RegBus_read_data,
  RegBus_access_complete,
  control_go,
  source_address_address,
  destination_address_address,
  length_length
  );

// Input declarations
  input           Clk;
  input           RegBus_read;
  input           RegBus_val;
  input [31:0]    RegBus_write_data;
  input [3:2]     RegBus_address;
  input           control_go_next;
  input           RESET;

// Output declarations
  output [31:0]   RegBus_read_data;
  output          RegBus_access_complete;
  output          control_go;
  output [29:0]   source_address_address;
  output [29:0]   destination_address_address;
  output [31:0]   length_length;

// Wire declarations
  wire            Clk;
  wire            RegBus_read;
  wire            RegBus_val;
  wire [31:0]     RegBus_read_data;
  wire [31:0]     RegBus_read_data_ucore;
  wire            RegBus_read_ucore;
  wire            RegBus_read_dcore;
  wire            RegBus_write_dcore;
  wire            RegBus_write_ucore;
  wire [31:0]     RegBus_write_data;
  wire [31:0]     RegBus_write_data_dcore;
  wire [31:0]     RegBus_write_data_ucore;
  wire            valid_RegBus_write;
  wire            RegBus_access_complete;
  wire            RegBus_access_complete_ucore;
  wire            RegBus_access_complete_dcore;
  wire [3:2]      RegBus_address;
  wire [3:2]      RegBus_address_ucore;
  wire [3:2]      RegBus_address_dcore;
  wire            RegBus_xfer_valid_internal;
  wire            control_full_read_data;
  wire            control_go__write;
  wire            control_go__sw_next;
  wire            control_go__swmod;
  wire            control_go_next;
  wire            control_go__field_next;
  wire            RESET;
  wire [31:2]     source_address_full_read_data;
  wire            source_address_address__write;
  wire [29:0]     source_address_address__sw_next;
  wire            source_address_address__swmod;
  wire [29:0]     source_address_address__field_next;
  wire [31:2]     destination_address_full_read_data;
  wire            destination_address_address__write;
  wire [29:0]     destination_address_address__sw_next;
  wire            destination_address_address__swmod;
  wire [29:0]     destination_address_address__field_next;
  wire [31:0]     length_full_read_data;
  wire            length_length__write;
  wire [31:0]     length_length__sw_next;
  wire            length_length__swmod;
  wire [31:0]     length_length__field_next;

// Reg declarations
  reg [31:0]      RegBus_read_data_dcore;
  reg             RegBus_access_complete_valid_internal;
  reg             RegBus_address_valid_internal;
  reg             RegBus_access_valid_internal;
  reg             control_decode;
  reg             control_go;
  reg             source_address_decode;
  reg [29:0]      source_address_address;
  reg             destination_address_decode;
  reg [29:0]      destination_address_address;
  reg             length_decode;
  reg [31:0]      length_length;

  // General CPU interface signal equations
  assign RegBus_read_data_ucore = RegBus_read_data_dcore;

  assign RegBus_read_ucore = RegBus_read & RegBus_val;

  assign RegBus_read_data = RegBus_read_data_ucore;

  assign RegBus_read_dcore = RegBus_read_ucore;

  assign RegBus_write_dcore = RegBus_write_ucore;

  assign RegBus_write_data_dcore = RegBus_write_data_ucore;

  assign RegBus_write_ucore = ~RegBus_read & RegBus_val;

  assign RegBus_write_data_ucore = RegBus_write_data;

  assign valid_RegBus_write = RegBus_xfer_valid_internal & RegBus_write_dcore;

  assign RegBus_access_complete_ucore = RegBus_access_complete_dcore;

  assign RegBus_access_complete_dcore = 
           (RegBus_read_dcore | RegBus_write_dcore) & 
           (RegBus_access_complete_valid_internal | 
           ~RegBus_xfer_valid_internal); 

  assign RegBus_access_complete = RegBus_access_complete_ucore;

  assign RegBus_address_ucore = RegBus_address;

  assign RegBus_address_dcore = RegBus_address_ucore;

  assign RegBus_xfer_valid_internal = 
           RegBus_address_valid_internal & RegBus_access_valid_internal ; 


  assign control_full_read_data = control_go;


  // Logic for control.go
  // Instantiated in file "soc_miner_regs.rdl":10
  assign control_go__write = valid_RegBus_write & control_decode;

  assign control_go__sw_next = RegBus_write_data_dcore[0];

  assign control_go__swmod = control_go__write;

  assign control_go__field_next = 
           ((control_go__swmod) 
             ? control_go__sw_next 
             : control_go_next); 

  always @(posedge Clk ) 
  begin 
    if (RESET)
      control_go <= 
      1'h0; 
    else
      control_go <= 
      control_go__field_next; 
  end


  assign source_address_full_read_data = source_address_address;


  // Logic for source_address.address
  // Instantiated in file "soc_miner_regs.rdl":2
  assign source_address_address__write = 
           valid_RegBus_write & source_address_decode; 

  assign source_address_address__sw_next = RegBus_write_data_dcore[31:2];

  assign source_address_address__swmod = source_address_address__write;

  assign source_address_address__field_next = 
           ((source_address_address__swmod) 
             ? source_address_address__sw_next 
             : source_address_address); 

  always @(posedge Clk ) 
  begin 
    if (RESET)
      source_address_address <= 
      30'h0; 
    else
      source_address_address <= 
      source_address_address__field_next; 
  end


  assign destination_address_full_read_data = destination_address_address;


  // Logic for destination_address.address
  // Instantiated in file "soc_miner_regs.rdl":2
  assign destination_address_address__write = 
           valid_RegBus_write & destination_address_decode; 

  assign destination_address_address__sw_next = RegBus_write_data_dcore[31:2];

  assign destination_address_address__swmod = 
           destination_address_address__write; 

  assign destination_address_address__field_next = 
           ((destination_address_address__swmod) 
             ? destination_address_address__sw_next 
             : destination_address_address); 

  always @(posedge Clk ) 
  begin 
    if (RESET)
      destination_address_address <= 
      30'h0; 
    else
      destination_address_address <= 
      destination_address_address__field_next; 
  end


  assign length_full_read_data = length_length;


  // Logic for length.length
  // Instantiated in file "soc_miner_regs.rdl":6
  assign length_length__write = valid_RegBus_write & length_decode;

  assign length_length__sw_next = RegBus_write_data_dcore[31:0];

  assign length_length__swmod = length_length__write;

  assign length_length__field_next = 
           ((length_length__swmod) 
             ? length_length__sw_next 
             : length_length); 

  always @(posedge Clk ) 
  begin 
    if (RESET)
      length_length <= 
      32'h0; 
    else
      length_length <= 
      length_length__field_next; 
  end


  always @( source_address_full_read_data or
           RegBus_address_dcore or
           length_full_read_data or
           destination_address_full_read_data or
           control_full_read_data ) begin

    RegBus_address_valid_internal = 1'b0;
    RegBus_access_valid_internal = 1'b0;
    RegBus_access_complete_valid_internal = 1'b0;
    control_decode = 1'b0;
    source_address_decode = 1'b0;
    destination_address_decode = 1'b0;
    length_decode = 1'b0;

    case(RegBus_address_dcore)
    // Register:     soc_miner_regs control
    // Full Address: 0x0 [0x0]
    2'b00:
      begin
        control_decode = 1'b1;
        RegBus_read_data_dcore = { 31'h00000000, control_full_read_data };
        RegBus_access_valid_internal = 1'b1;
        RegBus_address_valid_internal = 1'b1;
        RegBus_access_complete_valid_internal = 1'b1;
      end

    // Register:     soc_miner_regs source_address
    // Full Address: 0x4 [0x1]
    2'b01:
      begin
        source_address_decode = 1'b1;
        RegBus_read_data_dcore = { source_address_full_read_data, 2'h0 };
        RegBus_access_valid_internal = 1'b1;
        RegBus_address_valid_internal = 1'b1;
        RegBus_access_complete_valid_internal = 1'b1;
      end

    // Register:     soc_miner_regs destination_address
    // Full Address: 0x8 [0x2]
    2'b10:
      begin
        destination_address_decode = 1'b1;
        RegBus_read_data_dcore = { destination_address_full_read_data, 2'h0 };
        RegBus_access_valid_internal = 1'b1;
        RegBus_address_valid_internal = 1'b1;
        RegBus_access_complete_valid_internal = 1'b1;
      end

    // Register:     soc_miner_regs length
    // Full Address: 0xc [0x3]
    2'b11:
      begin
        length_decode = 1'b1;
        RegBus_read_data_dcore = length_full_read_data;
        RegBus_access_valid_internal = 1'b1;
        RegBus_address_valid_internal = 1'b1;
        RegBus_access_complete_valid_internal = 1'b1;
      end

    default: RegBus_read_data_dcore = 32'h00000000;
    endcase
  end

endmodule // soc_miner_regs

