# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/soc_miner_wrapper.xdc

# Block Designs: bd/soc_miner_io/soc_miner_io.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_miner_io || ORIG_REF_NAME==soc_miner_io}]

# IP: bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/soc_miner_io_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_miner_io_processing_system7_0_0 || ORIG_REF_NAME==soc_miner_io_processing_system7_0_0}]

# IP: bd/soc_miner_io/ip/soc_miner_io_axi_interconnect_0_0/soc_miner_io_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_miner_io_axi_interconnect_0_0 || ORIG_REF_NAME==soc_miner_io_axi_interconnect_0_0}]

# IP: bd/soc_miner_io/ip/soc_miner_io_axi_interconnect_1_1/soc_miner_io_axi_interconnect_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_miner_io_axi_interconnect_1_1 || ORIG_REF_NAME==soc_miner_io_axi_interconnect_1_1}]

# XDC: bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/soc_miner_io_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_miner_io_processing_system7_0_0 || ORIG_REF_NAME==soc_miner_io_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/soc_miner_io/soc_miner_io_ooc.xdc
