VCS=vcs
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_reg_init.v  
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_unused_ports.v	   
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_axi_acp.v    
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_axi_gp.v      	   
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_axi_hp.v      	   
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_apis.v		   
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_gen_reset.v   	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_intr_wr_mem.v 	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_ssw_hp.v      	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_intr_rd_mem.v 	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_regc.v		   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_reg_params.v  	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_ocmc.v		   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_arb_hp2_3.v   	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_fmsw_gp.v     	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_ddrc.v		   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_interconnect_model.v     \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_afi_slave.v   	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_reg_map.v     	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_arb_rd.v      	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_ocm_mem.v     	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_local_params.v	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_gen_clock.v   	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_axi_master.v  	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_arb_hp0_1.v   	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_sparse_mem.v  	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_arb_wr.v      	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_processing_system7_bfm.v \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_arb_rd_4.v    	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_arb_wr_4.v    	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/processing_system7_bfm_v2_0_axi_slave.v   	   \
#../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/sim/soc_miner_io_processing_system7_0_0.v     	   \

FILES= soc_miner_tb.sv \
../rtl/soc_miner_wrapper.v \
../rtl/axi4_if.sv \
../rtl/axi4lite_if.sv \
sys_fm.v \
../axi_example/hdl/verilog/axi_slave.v \
../axi_example/hdl/verilog/axi_lite_slave.v \
../axi_example/hdl/verilog/axi_stream_master.v \
../axi_example/hdl/verilog/axi_lite_master.v \
../axi_example/hdl/verilog/axi_master.v \
../axi_example/hdl/verilog/axi_stream_slave.v \
../rtl/axi4lite2regbus.sv \
../rtl/regbus_if.sv \
../rtl/soc_miner_regs.v \
../rtl/auto_clear.sv \
../rtl/soc_miner.sv \
../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/synth/soc_miner_io_processing_system7_0_0.v   	   \
../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/verilog/processing_system7_v5_3_processing_system7.v \
../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/verilog/processing_system7_v5_3_w_atc.v   	   \
../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/verilog/processing_system7_v5_3_b_atc.v   	   \
../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/verilog/processing_system7_v5_3_trace_buffer.v       \
../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/verilog/processing_system7_v5_3_atc.v     	   \
../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/verilog/processing_system7_v5_3_aw_atc.v  	   \
../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/hdl/soc_miner_io.v   									   \
../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/hdl/soc_miner_io_wrapper.v   								   

XILINX_FILES = -y /data/Xilinx/Vivado/2013.3/data/verilog/src/unisims \
	-y /data/Xilinx/Vivado/2013.3/data/verilog/src/unimacro \
	-y /data/Xilinx/Vivado/2013.3/data/verilog/src/retarget \
	-y /data/Xilinx/Vivado/2013.3/ids_lite/ISE/verilog/src/XilinxCoreLib \
	+incdir+/data/Xilinx/Vivado/2013.3/verilog/src +libext+.v \
        /data/Xilinx/Vivado/2013.3/data/verilog/src/glbl.v 

#	-f /data/Xilinx/Vivado/2013.3/data/secureip/secureip_cell.list.f \
#	-f /data/Xilinx/Vivado/2013.3/data/secureip/axi_bfm/axi_bfm_cell.list.f \
#	+incdir+/data/Xilinx/Vivado/2013.3/verilog/src +libext+.v \
#        /data/Xilinx/Vivado/2013.3/data/verilog/src/glbl.v \
#	+verilog2001ext+.vp \
#-lca -Mupdate -load /data/Xilinx/Vivado/2013.3/ids_lite/ISE/lib/lin/libxil_vcs.so
#TOP=axi_tb
#TOP=axi_lite_tb
#TOP=axi_lite_gasket_tb
INCDIRS=+incdir+../../syn/soc_miner_io/soc_miner_io.srcs/sources_1/bd/soc_miner_io/ip/soc_miner_io_processing_system7_0_0/hdl/
TOP=soc_miner_tb
#TOP=soc_miner_wrapper
#+lint=all -lca
OPTIONS= -l vcs.log -fsdb  -timescale=1ns/1ps  -sverilog
all:
	$(VCS) $(OPTIONS) -top $(TOP) $(INCDIRS) $(FILES) $(XILINX_FILES)
	./simv +UVM_TESTNAME=$(UVM_TESTNAME)

